language: java
git:
  submodules: false
sudo: required

before_install:
  - sudo apt-get install p7zip-full libx11-dev libxxf86vm-dev xvfb libgl1-mesa-dri
  - cd ..
  - git clone --recurse-submodules git://jogamp.org/srv/scm/gluegen.git gluegen
  - pushd gluegen/make
  - ant
  - popd
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pushd jogl/make
  - ant
  - ant junit.run
